streams-contrib/streams-provider-facebook/pom.xml
streams-contrib/streams-provider-facebook/src/main/java/org/apache/streams/facebook/provider/FacebookDataCollector.java
streams-contrib/streams-provider-facebook/src/main/java/org/apache/streams/facebook/provider/FacebookProvider.java
streams-contrib/streams-provider-facebook/src/main/java/org/apache/streams/facebook/provider/page/FacebookPageDataCollector.java
streams-contrib/streams-provider-facebook/src/main/java/org/apache/streams/facebook/provider/page/FacebookPageProvider.java
streams-contrib/streams-provider-facebook/src/main/java/org/apache/streams/facebook/provider/pagefeed/FacebookPageFeedDataCollector.java
streams-contrib/streams-provider-facebook/src/test/java/org/apache/streams/facebook/provider/page/TestFacebookPageProvider.java
streams-contrib/streams-provider-facebook/src/test/java/org/apache/streams/facebook/provider/page/TestPage.java
streams-contrib/streams-provider-facebook/src/test/java/org/apache/streams/facebook/provider/pagefeed/TestFacebookProvider.java

Created a Facebook Page/Bio Provider that follows the same paradigm set with the PageFeed provider.

STREAMS-261 | Facebook Page/Bio Provider

---

streams-components/streams-http/README.md
streams-components/streams-http/pom.xml
streams-components/streams-http/src/main/java/org/apache/streams/components/http/HttpConfigurator.java
streams-components/streams-http/src/main/java/org/apache/streams/components/http/persist/SimpleHTTPPostPersistWriter.java
streams-components/streams-http/src/main/java/org/apache/streams/components/http/processor/SimpleHTTPGetProcessor.java
streams-components/streams-http/src/main/jsonschema/org/apache/streams/components/http/HttpPersistWriterConfiguration.json
streams-components/streams-http/src/test/java/SimpleHTTPPostPersistWriterTest.java

creates SimpleHTTPPostPersistWriter
slight modify SimpleHttpGetProcessor to use the same methods

implementation and test for STREAMS-221

---

streams-contrib/streams-persist-elasticsearch/src/main/java/org/apache/streams/elasticsearch/ElasticsearchMetadataUtil.java
streams-contrib/streams-persist-elasticsearch/src/main/java/org/apache/streams/elasticsearch/ElasticsearchPersistReader.java
streams-contrib/streams-persist-elasticsearch/src/main/java/org/apache/streams/elasticsearch/ElasticsearchPersistWriter.java

NOTE: An integration test covering this feature will be included in a PR for https://issues.apache.org/jira/browse/STREAMS-287

resolves STREAMS-284.  tested locally

---

streams-contrib/streams-persist-hdfs/pom.xml
streams-contrib/streams-persist-hdfs/src/main/java/org/apache/streams/hdfs/HdfsConstants.java
streams-contrib/streams-persist-hdfs/src/main/java/org/apache/streams/hdfs/WebHdfsPersistReader.java
streams-contrib/streams-persist-hdfs/src/main/java/org/apache/streams/hdfs/WebHdfsPersistReaderTask.java
streams-contrib/streams-persist-hdfs/src/main/java/org/apache/streams/hdfs/WebHdfsPersistWriter.java
streams-contrib/streams-persist-hdfs/src/main/jsonschema/org/apache/streams/hdfs/HdfsConfiguration.json
streams-contrib/streams-persist-hdfs/src/test/java/org/apache/streams/hdfs/test/TestHdfsPersist.java

STREAMS-293

---

streams-components/streams-converters/src/main/java/org/apache/streams/converter/HoconConverterProcessor.java
streams-components/streams-converters/src/main/java/org/apache/streams/converter/HoconConverterUtil.java
streams-components/streams-converters/src/test/java/org/apache/streams/converter/test/HoconConverterProcessorTest.java
streams-components/streams-converters/src/test/java/org/apache/streams/converter/test/HoconConverterTest.java
streams-components/streams-converters/src/test/resources/test1.conf
streams-components/streams-converters/src/test/resources/test2.conf
streams-components/streams-converters/src/test/resources/test3a.conf
streams-components/streams-converters/src/test/resources/test3b.conf

includes tests demonstrating concept of use

resolves STREAMS-301

---

README.md

resolves STREAMS-271

---

streams-contrib/streams-persist-graph/pom.xml

Signed-off-by: Steve Blackmon (@steveblackmon) <sblackmon@apache.org>

attempt to fix jenkins test failure

---

streams-contrib/streams-persist-graph/src/test/java/org/apache/streams/graph/test/TestNeo4jVertexReader.java

Signed-off-by: Steve Blackmon (@steveblackmon) <sblackmon@apache.org>

attempt to fix jenkins test failure take 2

---

streams-runtimes/streams-runtime-local/src/main/java/org/apache/streams/local/builders/LocalStreamBuilder.java

Signed-off-by: Steve Blackmon (@steveblackmon) <sblackmon@apache.org>

logging tweak for accuracy

---

streams-components/streams-converters/src/main/java/org/apache/streams/converter/ActivityConverterUtil.java
streams-components/streams-converters/src/main/java/org/apache/streams/converter/HoconConverterProcessor.java
streams-components/streams-converters/src/main/java/org/apache/streams/converter/HoconConverterUtil.java
streams-components/streams-converters/src/main/java/org/apache/streams/converter/TypeConverterProcessor.java
streams-components/streams-converters/src/main/java/org/apache/streams/converter/TypeConverterUtil.java
streams-components/streams-converters/src/test/java/org/apache/streams/converter/test/HoconConverterProcessorTest.java
streams-components/streams-converters/src/test/java/org/apache/streams/converter/test/HoconConverterTest.java
streams-components/streams-converters/src/test/resources/test4.conf

while I was working in this module, switched Hocon Type and Activity Util classes from static to singleton accessor which are much easier to use in scala/spark

resolves STREAMS-321 #321

---

streams-config/src/main/jsonschema/StreamsConfiguration.json
streams-monitoring/src/main/java/org/apache/streams/monitoring/tasks/BroadcastMonitorThread.java
streams-monitoring/src/test/java/org/apache/streams/monitoring/tasks/BroadcastMonitorThreadTest.java
streams-runtimes/streams-runtime-dropwizard/src/main/java/org/apache/streams/dropwizard/StreamDropwizardBuilder.java
streams-runtimes/streams-runtime-dropwizard/src/main/java/org/apache/streams/dropwizard/StreamsApplication.java
streams-runtimes/streams-runtime-local/src/main/java/org/apache/streams/local/builders/LocalStreamBuilder.java
streams-runtimes/streams-runtime-local/src/main/java/org/apache/streams/local/builders/StreamComponent.java
streams-runtimes/streams-runtime-local/src/main/java/org/apache/streams/local/tasks/BaseStreamsTask.java
streams-runtimes/streams-runtime-local/src/main/java/org/apache/streams/local/tasks/StreamsMergeTask.java
streams-runtimes/streams-runtime-local/src/main/java/org/apache/streams/local/tasks/StreamsPersistWriterTask.java
streams-runtimes/streams-runtime-local/src/main/java/org/apache/streams/local/tasks/StreamsProcessorTask.java
streams-runtimes/streams-runtime-local/src/main/java/org/apache/streams/local/tasks/StreamsProviderTask.java
streams-runtimes/streams-runtime-local/src/main/java/org/apache/streams/local/tasks/StreamsTask.java
streams-runtimes/streams-runtime-local/src/main/jsonschema/LocalRuntimeConfiguration.json
streams-runtimes/streams-runtime-local/src/test/java/org/apache/streams/local/tasks/BasicTasksTest.java

completed, all tests passing
resolves #226
resolves #294
resolves #325

Streams 226

---

.travis.yml

resolves STREAMS-331 #331

---

pom.xml
streams-components/streams-http/pom.xml
streams-contrib/streams-amazon-aws/streams-persist-s3/pom.xml
streams-contrib/streams-persist-cassandra/pom.xml
streams-contrib/streams-persist-hbase/pom.xml
streams-contrib/streams-persist-hdfs/pom.xml
streams-contrib/streams-processor-urls/pom.xml
streams-contrib/streams-provider-google/google-gmail/pom.xml
streams-contrib/streams-provider-google/google-gplus/pom.xml
streams-contrib/streams-provider-rss/pom.xml
streams-contrib/streams-provider-twitter/pom.xml
streams-contrib/streams-provider-youtube/pom.xml
streams-monitoring/pom.xml
streams-osgi-components/activity-consumer/pom.xml
streams-runtimes/streams-runtime-local/pom.xml
streams-runtimes/streams-runtime-pig/pom.xml
streams-runtimes/streams-runtime-storm/pom.xml
streams-runtimes/streams-runtime-webapp/pom.xml

consolidated plugin versions and configuration into streams-master
more exclusions to meet enforcer criteria re logging
build and tests passing here

resolves STREAMS-336 #336 for incubator-streams

---

streams-components/streams-http/src/main/java/org/apache/streams/components/http/persist/SimpleHTTPPostPersistWriter.java
streams-contrib/streams-persist-graph/pom.xml
streams-contrib/streams-persist-graph/src/main/java/org/apache/streams/graph/GraphHttpPersistWriter.java
streams-contrib/streams-persist-graph/src/main/java/org/apache/streams/graph/neo4j/CypherQueryGraphHelper.java
streams-contrib/streams-persist-graph/src/main/java/org/apache/streams/graph/neo4j/Neo4jHttpGraphHelper.java
streams-contrib/streams-persist-graph/src/test/java/org/apache/streams/graph/test/TestCypherQueryGraphHelper.java

introduced with first STREAMS-313 PR, added test case

found and fixed a bug with GraphHttpPersistWriter

---

streams-contrib/streams-persist-hdfs/pom.xml
streams-contrib/streams-persist-hdfs/src/main/java/org/apache/streams/hdfs/WebHdfsPersistReader.java
streams-contrib/streams-persist-hdfs/src/main/java/org/apache/streams/hdfs/WebHdfsPersistReaderTask.java

general improvement to logging
use a predictable file ordering when processing a directory

resolves STREAMS-346

---

streams-config/src/main/jsonschema/StreamsConfiguration.json
streams-monitoring/src/main/java/org/apache/streams/monitoring/tasks/BroadcastMonitorThread.java
streams-runtimes/streams-runtime-local/src/main/java/org/apache/streams/local/builders/LocalStreamBuilder.java
streams-runtimes/streams-runtime-local/src/main/java/org/apache/streams/local/tasks/StreamsPersistWriterTask.java
streams-runtimes/streams-runtime-local/src/main/java/org/apache/streams/local/tasks/StreamsProcessorTask.java

now we can keep a stream alive for a minimum duration and change how often to check for a shutdown condition

resolves STREAMS-357

---

streams-contrib/streams-persist-elasticsearch/src/main/java/org/apache/streams/elasticsearch/ElasticsearchPersistWriter.java
streams-contrib/streams-persist-elasticsearch/src/main/java/org/apache/streams/elasticsearch/ElasticsearchQuery.java
streams-contrib/streams-persist-elasticsearch/src/main/jsonschema/org/apache/streams/elasticsearch/ElasticsearchWriterConfiguration.json

now you have to explicitly ask for a refresh for a refresh to occur

resolves STREAMS-358

---

streams-components/streams-converters/src/main/java/org/apache/streams/converter/FieldConstants.java
streams-components/streams-converters/src/main/java/org/apache/streams/converter/LineReadWriteUtil.java
streams-components/streams-converters/src/main/java/org/apache/streams/converter/TypeConverterUtil.java
streams-components/streams-converters/src/test/java/org/apache/streams/converter/test/TestLineReadWriteUtil.java
streams-contrib/streams-amazon-aws/streams-persist-s3/pom.xml
streams-contrib/streams-amazon-aws/streams-persist-s3/src/main/java/org/apache/streams/s3/S3PersistReader.java
streams-contrib/streams-amazon-aws/streams-persist-s3/src/main/java/org/apache/streams/s3/S3PersistReaderTask.java
streams-contrib/streams-amazon-aws/streams-persist-s3/src/main/java/org/apache/streams/s3/S3PersistWriter.java
streams-contrib/streams-amazon-aws/streams-persist-s3/src/main/jsonschema/org/apache/streams/s3/S3Configuration.json
streams-contrib/streams-amazon-aws/streams-persist-s3/src/main/jsonschema/org/apache/streams/s3/S3WriterConfiguration.json
streams-contrib/streams-persist-hdfs/pom.xml
streams-contrib/streams-persist-hdfs/src/main/java/org/apache/streams/hdfs/WebHdfsPersistReader.java
streams-contrib/streams-persist-hdfs/src/main/java/org/apache/streams/hdfs/WebHdfsPersistReaderTask.java
streams-contrib/streams-persist-hdfs/src/main/java/org/apache/streams/hdfs/WebHdfsPersistWriter.java

refactors persist-hdfs and persist-s3 to use LineReadWriteUtil
adds TestLineReadWriteUtil

Streams 363

---

streams-components/streams-converters/src/main/java/org/apache/streams/converter/BaseDocumentClassifier.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/converter/TwitterDocumentClassifier.java
streams-contrib/streams-provider-twitter/src/test/java/org/apache/streams/twitter/test/utils/TwitterActivityConvertersTest.java
streams-contrib/streams-provider-twitter/src/test/java/org/apache/streams/twitter/test/utils/TwitterActivityObjectsConvertersTest.java

no reason to limit these classes to String and ObjectNode input documents
adds testing to ensure typed object and string json versions both work

resolves STREAMS-427

---

streams-contrib/streams-provider-youtube/pom.xml
streams-contrib/streams-provider-youtube/src/main/java/com/youtube/provider/YoutubeChannelDataCollector.java
streams-contrib/streams-provider-youtube/src/main/java/com/youtube/provider/YoutubeChannelProvider.java
streams-contrib/streams-provider-youtube/src/main/java/com/youtube/provider/YoutubeProvider.java
streams-contrib/streams-provider-youtube/src/main/java/com/youtube/provider/YoutubeUserActivityCollector.java
streams-contrib/streams-provider-youtube/src/main/java/com/youtube/provider/YoutubeUserActivityProvider.java
streams-contrib/streams-provider-youtube/src/site/markdown/index.md
streams-contrib/streams-provider-youtube/src/test/java/org/apache/streams/youtube/test/providers/YoutubeChannelProviderIT.java
streams-contrib/streams-provider-youtube/src/test/java/org/apache/streams/youtube/test/providers/YoutubeUserActivityProviderIT.java
streams-contrib/streams-provider-youtube/src/test/resources/YoutubeChannelProviderIT.conf
streams-contrib/streams-provider-youtube/src/test/resources/YoutubeUserActivityProviderIT.conf

add console support and integration testing for youtube providers

0.4 youtube

---

streams-contrib/streams-provider-google/google-gplus/pom.xml
streams-contrib/streams-provider-google/google-gplus/src/main/java/com/google/gplus/serializer/util/GPlusActivityDeserializer.java
streams-contrib/streams-provider-google/google-gplus/src/main/java/com/google/gplus/serializer/util/GPlusPersonDeserializer.java
streams-contrib/streams-provider-google/google-gplus/src/test/java/org/apache/streams/gplus/test/processors/GooglePlusTypeConverterIT.java
streams-contrib/streams-provider-google/google-gplus/src/test/java/org/apache/streams/gplus/test/providers/GPlusUserActivityProviderIT.java
streams-contrib/streams-provider-google/google-gplus/src/test/java/org/apache/streams/gplus/test/providers/GPlusUserDataProviderIT.java
streams-contrib/streams-provider-google/google-gplus/src/test/resources/GPlusUserActivityProviderIT.conf
streams-contrib/streams-provider-google/google-gplus/src/test/resources/GPlusUserDataProviderIT.conf

rebased, same code as https://github.com/apache/incubator-streams/pull/331

Streams 458

---

streams-contrib/streams-persist-elasticsearch/src/main/java/org/apache/streams/elasticsearch/ElasticsearchPersistReader.java
streams-contrib/streams-persist-hdfs/src/main/java/org/apache/streams/hdfs/WebHdfsPersistReader.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterStreamProvider.java

bug introduced in the last commit

Fix issue with streams-examples failing due to private scope of STREAMS_ID

---

streams-contrib/pom.xml
streams-contrib/streams-persist-cassandra/README.md
streams-contrib/streams-persist-cassandra/pom.xml
streams-contrib/streams-persist-cassandra/src/main/java/org/apache/streams/cassandra/CassandraPersistReader.java
streams-contrib/streams-persist-cassandra/src/main/java/org/apache/streams/cassandra/CassandraPersistWriter.java
streams-contrib/streams-persist-cassandra/src/main/jsonschema/org/apache/streams/cassandra/CassandraConfiguration.json
streams-contrib/streams-persist-cassandra/src/main/resources/cassandra.conf
streams-contrib/streams-persist-cassandra/src/main/resources/components.dot
streams-contrib/streams-persist-cassandra/src/site/markdown/cassandra.md
streams-contrib/streams-persist-cassandra/src/site/markdown/index.md
streams-contrib/streams-persist-cassandra/src/site/site.xml
streams-contrib/streams-persist-cassandra/src/test/java/org/apache/streams/cassandra/test/CassandraPersistIT.java
streams-contrib/streams-persist-cassandra/src/test/resources/CassandraPersistIT.conf

This issue is created to propose the streams persist reader/writer to get/post documents from/to apache cassandra.

[STREAMS-478] streams persist reader/writer for Apache Cassandra

---

pom.xml
streams-contrib/streams-persist-elasticsearch/pom.xml
streams-contrib/streams-persist-elasticsearch/src/main/java/org/apache/streams/elasticsearch/processor/DatumFromMetadataAsDocumentProcessor.java
streams-contrib/streams-persist-elasticsearch/src/main/java/org/apache/streams/elasticsearch/processor/DocumentToMetadataProcessor.java
streams-contrib/streams-persist-elasticsearch/src/main/java/org/apache/streams/elasticsearch/processor/MetadataFromDocumentProcessor.java
streams-contrib/streams-processor-jackson/src/main/java/org/apache/streams/jackson/CleanAdditionalPropertiesProcessor.java
streams-contrib/streams-processor-json/src/main/java/org/apache/streams/json/JsonPathExtractor.java
streams-contrib/streams-processor-json/src/main/java/org/apache/streams/json/JsonPathFilter.java
streams-contrib/streams-provider-moreover/pom.xml
streams-core/pom.xml

Remove jackson-datatype-json-org from project

STREAMS-500: Remove jackson-datatype-json-org from project

---

streams-config/pom.xml
streams-plugins/streams-plugin-pojo/pom.xml
streams-plugins/streams-plugin-pojo/src/main/java/org/apache/streams/plugins/JuneauPojoAnnotator.java
streams-plugins/streams-plugin-pojo/src/main/java/org/apache/streams/plugins/StreamsPojoGenerationConfig.java
streams-pojo/pom.xml

also add juneau-core to streams-pojo and streams-config

STREAMS-512: add juneau annotations to all generated pojos

---

pom.xml
streams-config/pom.xml
streams-contrib/streams-amazon-aws/pom.xml
streams-contrib/streams-amazon-aws/streams-persist-kinesis/pom.xml
streams-contrib/streams-amazon-aws/streams-persist-s3/pom.xml
streams-contrib/streams-persist-cassandra/pom.xml
streams-contrib/streams-persist-elasticsearch/pom.xml
streams-contrib/streams-persist-mongo/pom.xml
streams-contrib/streams-persist-neo4j/pom.xml
streams-contrib/streams-persist-riak/pom.xml
streams-contrib/streams-processor-json/src/main/java/org/apache/streams/json/JsonPathExtractor.java
streams-contrib/streams-provider-facebook/pom.xml
streams-contrib/streams-provider-facebook/src/test/java/org/apache/streams/facebook/test/TestPage.java
streams-contrib/streams-provider-rss/pom.xml
streams-plugins/pom.xml
streams-plugins/streams-plugin-cassandra/pom.xml
streams-plugins/streams-plugin-elasticsearch/pom.xml
streams-plugins/streams-plugin-hbase/pom.xml
streams-plugins/streams-plugin-hive/pom.xml
streams-plugins/streams-plugin-pig/pom.xml
streams-plugins/streams-plugin-pojo/pom.xml
streams-plugins/streams-plugin-scala/pom.xml
streams-pojo/pom.xml
streams-schemas/streams-schema-activitystreams/pom.xml
streams-util/pom.xml

this bumps many dependencies to their latest release version
plus a lot of incidental pom consolidation
all unit tests passing

STREAMS-523: global dependency version bump

---

pom.xml

plus some improvements to memory management

STREAMS-528 - add quick profile, enable by default

---

streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/api/Friendships.java
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/api/FriendshipCreateRequest.json
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/api/FriendshipDestroyRequest.json
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/api/FriendshipShowRequest.json
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/api/FriendshipShowResponse.json
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/api/FriendshipUpdateRequest.json
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/api/FriendshipsLookupRequest.json
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/api/FriendshipsOutgoingRequest.json
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/pojo/Friendship.json
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/pojo/Relationship.json
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/pojo/RelationshipSource.json
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/pojo/RelationshipTarget.json

Implement the /friendships endpoint in streams-provider-twitter

STREAMS-531: Implement the /friendships endpoint in streams-provider-twitter

---

streams-config/src/main/java/org/apache/streams/config/StreamsConfigurator.java
streams-config/src/test/java/org/apache/streams/config/test/StreamsConfiguratorTest.java
streams-config/src/test/resources/evenmore.conf
streams-config/src/test/resources/more.conf
streams-config/src/test/resources/testResolve.conf
streams-contrib/streams-amazon-aws/streams-persist-kinesis/src/main/java/org/apache/streams/amazon/kinesis/KinesisPersistReader.java
streams-contrib/streams-amazon-aws/streams-persist-kinesis/src/main/java/org/apache/streams/amazon/kinesis/KinesisPersistWriter.java
streams-contrib/streams-persist-neo4j/src/main/java/org/apache/streams/neo4j/http/Neo4jHttpPersistReader.java
streams-contrib/streams-persist-neo4j/src/main/java/org/apache/streams/neo4j/http/Neo4jHttpPersistWriter.java
streams-contrib/streams-provider-facebook/src/main/java/org/apache/streams/facebook/provider/FacebookFriendFeedProvider.java
streams-contrib/streams-provider-facebook/src/main/java/org/apache/streams/facebook/provider/FacebookFriendUpdatesProvider.java
streams-contrib/streams-provider-facebook/src/main/java/org/apache/streams/facebook/provider/FacebookProvider.java
streams-contrib/streams-provider-facebook/src/main/java/org/apache/streams/facebook/provider/FacebookUserInformationProvider.java
streams-contrib/streams-provider-facebook/src/main/java/org/apache/streams/facebook/provider/FacebookUserstreamProvider.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/processor/FetchAndReplaceTwitterProcessor.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterStreamProvider.java

made StreamsConfigurator.config private
new addConfig method

STREAMS-529: update data behind StreamsConfigurator

---

pom.xml
streams-components/streams-converters/pom.xml
streams-plugins/streams-plugin-cassandra/pom.xml
streams-plugins/streams-plugin-elasticsearch/pom.xml
streams-plugins/streams-plugin-hbase/pom.xml
streams-plugins/streams-plugin-hive/pom.xml
streams-plugins/streams-plugin-pig/pom.xml
streams-plugins/streams-plugin-pojo/pom.xml
streams-plugins/streams-plugin-scala/pom.xml
streams-pojo/pom.xml

(https://issues.apache.org/jira/browse/STREAMS-525)

STREAMS-525: discontinue use of reflections-maven

---

streams-contrib/streams-provider-facebook/src/main/java/org/apache/streams/facebook/provider/FacebookFriendFeedProvider.java
streams-contrib/streams-provider-google/google-gplus/src/main/java/org/apache/streams/gplus/provider/GPlusUserActivityCollector.java
streams-contrib/streams-provider-instagram/src/main/java/org/apache/streams/instagram/provider/recentmedia/InstagramRecentMediaCollector.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterFollowersIdsProviderTask.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterFollowersListProviderTask.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterFollowingProvider.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterFriendsIdsProviderTask.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterFriendsListProviderTask.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterTimelineProviderTask.java
streams-contrib/streams-provider-youtube/src/main/java/org/apache/streams/youtube/provider/YoutubeChannelDataCollector.java
streams-contrib/streams-provider-youtube/src/main/java/org/apache/streams/youtube/provider/YoutubeUserActivityCollector.java

https://issues.apache.org/jira/browse/STREAMS-530

STREAMS-530: Log the page_count, item_count, last_count when providers shut down

---

streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterFollowingProvider.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterFriendsListProviderTask.java
streams-contrib/streams-provider-twitter/src/test/java/org/apache/streams/twitter/test/data/TwitterObjectMapperIT.java
streams-contrib/streams-provider-twitter/src/test/java/org/apache/streams/twitter/test/providers/TwitterFollowingProviderIT.java
streams-contrib/streams-provider-twitter/src/test/java/org/apache/streams/twitter/test/providers/TwitterStreamProviderIT.java
streams-contrib/streams-provider-twitter/src/test/java/org/apache/streams/twitter/test/providers/TwitterTimelineProviderIT.java
streams-contrib/streams-provider-twitter/src/test/resources/TwitterFollowingProviderIT.conf

ids_only=false for friends/followers now works
https://issues.apache.org/jira/browse/STREAMS-532

STREAMS-532: ids_only=false for friends/followers

---

pom.xml

STREAMS-539: quick profile should be disabled by default (https://issues.apache.org/jira/browse/STREAMS-539)

STREAMS-539: quick profile should be disabled by default

---

pom.xml

(https://issues.apache.org/jira/browse/STREAMS-546)

STREAMS-546: Allow rat plugin to ignore .conf files in project root

---

streams-config/src/test/resources/testResolve.conf
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/api/Media.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/api/TwitterSecurity.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/api/WelcomeMessageRules.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/api/WelcomeMessages.java
streams-monitoring/src/main/resources/reference.conf
streams-runtimes/streams-runtime-local/src/main/resources/reference.conf

(https://issues.apache.org/jira/browse/STREAMS-547)

STREAMS-547: add any missing AL headers

---

pom.xml

https://issues.apache.org/jira/browse/STREAMS-548

STREAMS-548: update juneau dependency to 7.0.0

---

pom.xml

(https://issues.apache.org/jira/browse/STREAMS-493)

STREAMS-493: streams-examples jenkins build fails

---

streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/api/SevenDaySearch.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/api/SuggestedUsers.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/api/Twitter.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/api/Users.java
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/api/SevenDaySearchRequest.json
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/api/SevenDaySearchResponse.json
streams-contrib/streams-provider-twitter/src/test/java/org/apache/streams/twitter/test/api/TwitterIT.java

Results :
Tests run: 25, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] --- maven-failsafe-plugin:2.19.1:verify (integration-tests) @ streams-provider-twitter ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:05 min
[INFO] Finished at: 2017-10-27T15:00:26-05:00
[INFO] Final Memory: 59M/742M
[INFO] ------------------------------------------------------------------------

STREAMS_534_STREAMS_535

---

streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/api/Twitter.java
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/config/TwitterConfiguration.json
streams-contrib/streams-provider-twitter/src/main/resources/reference.conf
streams-contrib/streams-provider-twitter/src/test/resources/TwitterIT.conf

STREAMS-552: Disable .debug() by default in org.apache.streams.twitter.api.Twitter (https://issues.apache.org/jira/browse/STREAMS-552)

STREAMS-552

---

streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/api/ThirtyDaySearch.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/api/ThirtyDaySearchCounts.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/api/Twitter.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/search/SearchUtil.java
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/api/ThirtyDaySearchCountsRequest.json
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/api/ThirtyDaySearchCountsResponse.json
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/api/ThirtyDaySearchRequest.json
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/api/ThirtyDaySearchResponse.json
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/search/SearchGroups.json
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/search/ThirtyDaySearchOperator.json
streams-contrib/streams-provider-twitter/src/test/java/org/apache/streams/twitter/test/api/TwitterIT.java
streams-contrib/streams-provider-twitter/src/test/java/org/apache/streams/twitter/test/search/SearchUtilTest.java

STREAMS-553: Implement Premium Search in streams-provider-twitter (https://issues.apache.org/jira/browse/STREAMS-553)

STREAMS-553: Implement Premium Search in streams-provider-twitter

---

streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/api/SevenDaySearch.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/SevenDaySearchProvider.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/SevenDaySearchProviderTask.java
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/config/SevenDaySearchProviderConfiguration.json
streams-contrib/streams-provider-twitter/src/test/java/org/apache/streams/twitter/test/providers/TwitterSevenDaySearchProviderIT.java
streams-contrib/streams-provider-twitter/src/test/resources/TwitterSevenDaySearchProviderIT.conf

(https://issues.apache.org/jira/browse/STREAMS-556)

STREAMS-556: Twitter: SevenDaySearchProvider

---

streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/api/ThirtyDaySearch.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/ThirtyDaySearchProvider.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/ThirtyDaySearchProviderTask.java
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/config/ThirtyDaySearchProviderConfiguration.json
streams-contrib/streams-provider-twitter/src/test/java/org/apache/streams/twitter/test/providers/TwitterThirtyDaySearchProviderIT.java
streams-contrib/streams-provider-twitter/src/test/resources/TwitterThirtyDaySearchProviderIT.conf

STREAMS-566: Twitter: ThirtyDaySearchProvider (https://issues.apache.org/jira/browse/STREAMS-566)

STREAMS-566: Twitter: ThirtyDaySearchProvider

---

pom.xml

STREAMS-564: Update dependency versions on juneau and httpclient (https://issues.apache.org/jira/browse/STREAMS-564)

STREAMS-564

---

streams-contrib/streams-provider-instagram/src/main/java/org/apache/streams/instagram/provider/InstagramAbstractProvider.java
streams-contrib/streams-provider-instagram/src/main/java/org/apache/streams/instagram/provider/InstagramCommentsCollector.java
streams-contrib/streams-provider-instagram/src/main/java/org/apache/streams/instagram/provider/InstagramCommentsProvider.java
streams-contrib/streams-provider-instagram/src/main/java/org/apache/streams/instagram/provider/InstagramDataCollector.java
streams-contrib/streams-provider-instagram/src/main/java/org/apache/streams/instagram/provider/InstagramEngagersCollector.java
streams-contrib/streams-provider-instagram/src/main/java/org/apache/streams/instagram/provider/InstagramEngagersProvider.java
streams-contrib/streams-provider-instagram/src/main/java/org/apache/streams/instagram/provider/InstagramLikersCollector.java
streams-contrib/streams-provider-instagram/src/main/java/org/apache/streams/instagram/provider/InstagramLikersProvider.java
streams-contrib/streams-provider-instagram/src/main/java/org/apache/streams/instagram/provider/recentmedia/InstagramRecentMediaCollector.java
streams-contrib/streams-provider-instagram/src/main/java/org/apache/streams/instagram/provider/userinfo/InstagramUserInfoCollector.java
streams-contrib/streams-provider-instagram/src/main/jsonschema/org/apache/streams/instagram/config/InstagramCommentsProviderConfiguration.json
streams-contrib/streams-provider-instagram/src/main/jsonschema/org/apache/streams/instagram/config/InstagramConfiguration.json
streams-contrib/streams-provider-instagram/src/main/jsonschema/org/apache/streams/instagram/config/InstagramEngagersProviderConfiguration.json
streams-contrib/streams-provider-instagram/src/main/jsonschema/org/apache/streams/instagram/config/InstagramLikersProviderConfiguration.json
streams-contrib/streams-provider-instagram/src/main/resources/reference.conf
streams-contrib/streams-provider-instagram/src/test/java/org/apache/streams/instagram/test/data/InstagramMediaFeedDataConverterIT.java
streams-contrib/streams-provider-instagram/src/test/java/org/apache/streams/instagram/test/data/InstagramUserInfoDataConverterIT.java
streams-contrib/streams-provider-instagram/src/test/java/org/apache/streams/instagram/test/providers/InstagramCommentsProviderIT.java
streams-contrib/streams-provider-instagram/src/test/java/org/apache/streams/instagram/test/providers/InstagramEngagersProviderIT.java
streams-contrib/streams-provider-instagram/src/test/java/org/apache/streams/instagram/test/providers/InstagramLikersProviderIT.java
streams-contrib/streams-provider-instagram/src/test/java/org/apache/streams/instagram/test/providers/InstagramUserInfoProviderIT.java
streams-contrib/streams-provider-instagram/src/test/resources/InstagramCommentsProviderIT.conf
streams-contrib/streams-provider-instagram/src/test/resources/InstagramEngagersProviderIT.conf
streams-contrib/streams-provider-instagram/src/test/resources/InstagramLikersProviderIT.conf

InstagramLikers[Collector,Provider]: Likers from a set of post ids
InstagramCollects[Collector,Provider]: Comments for a set of post ids
InstagramEngagers[Collector,Provider]: Likers and Commenters for a user’s recent posts

STREAMS-560: Instagram: Likes Provider

---

streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/api/Statuses.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/api/Twitter.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterEngagersProvider.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterRetweeterIdsTask.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterRetweetsTask.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterUserInformationProvider.java
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/api/RetweeterIdsRequest.json
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/api/RetweeterIdsResponse.json
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/api/RetweetsRequest.json
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/config/TwitterEngagersProviderConfiguration.json
streams-contrib/streams-provider-twitter/src/test/java/org/apache/streams/twitter/test/api/TwitterIT.java
streams-contrib/streams-provider-twitter/src/test/java/org/apache/streams/twitter/test/providers/TwitterEngagersProviderIT.java
streams-contrib/streams-provider-twitter/src/test/resources/TwitterEngagersProviderIT.conf

Twitter.java: Support for collecting retweets and retweeters of a post.
TwitterEngagersProvider.java: A new provider that collects all available retweeters across a full timeline for specified user(s)

STREAMS-550: Twitter: Retweets Provider

---

streams-config/src/test/java/org/apache/streams/config/test/ComponentConfigurationForTestingNumberOne.java
streams-config/src/test/java/org/apache/streams/config/test/ComponentConfigurationForTestingNumberTwo.java
streams-config/src/test/java/org/apache/streams/config/test/StreamsConfigurationForTesting.java
streams-config/src/test/resources/canonicalClassName.conf
streams-config/src/test/resources/classHierarchy.conf
streams-config/src/test/resources/packageHierarchy.conf
streams-config/src/test/resources/packagePath.conf
streams-config/src/test/resources/simpleClassName.conf

missing apache license headers

resolves STREAMS-587

---

pom.xml
streams-dist/pom.xml

build an uber-jar by enabling the dist profile

resolves STREAMS-551

---

pom.xml
src/license/THIRD-PARTY.properties
streams-plugins/streams-plugin-pojo/pom.xml
streams-pojo/pom.xml
streams-runtimes/streams-runtime-dropwizard/pom.xml
streams-runtimes/streams-runtime-dropwizard/src/test/java/org/apache/streams/dropwizard/test/GenericWebhookResourceTest.java
streams-runtimes/streams-runtime-local/pom.xml
streams-util/pom.xml
streams-util/src/test/resources/application.conf

excludes all identified problematic third-party dependencies
disables one test which began failing with org.jboss.logging:jboss-logging excluded

resolves STREAMS-591

---

pom.xml

Move execution of maven-enforcer-plugin under the check profile

---

streams-dist/pom.xml
streams-dist/src/main/assembly/assembly-dist.xml

Add a distribution binary

---

pom.xml

fix strangeness with enforcer

---

README.md
pom.xml
streams-contrib/streams-persist-console/README.md
streams-contrib/streams-persist-hbase/src/main/resources/reference.properties
streams-contrib/streams-persist-kafka/src/main/resources/reference.properties
streams-contrib/streams-provider-facebook/README.md
streams-contrib/streams-provider-google/google-gmail/README.md
streams-contrib/streams-provider-google/google-gplus/README.md

Prune RAT plugin configurations' exclusions settings.

---

streams-contrib/streams-persist-cassandra/pom.xml
streams-contrib/streams-persist-cassandra/src/test/java/org/apache/streams/cassandra/test/CassandraPersistIT.java
streams-contrib/streams-persist-cassandra/src/test/resources/application.conf
streams-contrib/streams-persist-elasticsearch/pom.xml
streams-contrib/streams-persist-elasticsearch/src/test/java/org/apache/streams/elasticsearch/test/ElasticsearchParentChildUpdaterIT.java
streams-contrib/streams-persist-elasticsearch/src/test/java/org/apache/streams/elasticsearch/test/ElasticsearchParentChildWriterIT.java
streams-contrib/streams-persist-elasticsearch/src/test/java/org/apache/streams/elasticsearch/test/ElasticsearchPersistUpdaterIT.java
streams-contrib/streams-persist-elasticsearch/src/test/java/org/apache/streams/elasticsearch/test/ElasticsearchPersistWriterIT.java
streams-contrib/streams-persist-elasticsearch/src/test/resources/application.conf
streams-contrib/streams-persist-hbase/src/test/resources/application.conf
streams-contrib/streams-persist-mongo/pom.xml
streams-contrib/streams-persist-mongo/src/test/java/org/apache/streams/mongo/test/MongoPersistIT.java
streams-contrib/streams-persist-mongo/src/test/resources/application.conf
streams-contrib/streams-persist-neo4j/pom.xml
streams-contrib/streams-persist-neo4j/src/test/java/org/apache/streams/neo4j/test/Neo4jBoltPersistIT.java
streams-contrib/streams-persist-neo4j/src/test/java/org/apache/streams/neo4j/test/Neo4jHttpPersistIT.java
streams-contrib/streams-persist-neo4j/src/test/resources/application.conf
streams-contrib/streams-persist-riak/pom.xml
streams-contrib/streams-persist-riak/src/test/java/org/apache/streams/riak/test/RiakBinaryPersistIT.java
streams-contrib/streams-persist-riak/src/test/java/org/apache/streams/riak/test/RiakHttpPersistIT.java
streams-contrib/streams-persist-riak/src/test/resources/application.conf

fix streams-persist ITs

---

streams-config/src/test/resources/application.conf
streams-examples/streams-examples-local/elasticsearch-hdfs/pom.xml
streams-examples/streams-examples-local/elasticsearch-hdfs/src/test/resources/application.conf
streams-examples/streams-examples-local/elasticsearch-reindex/pom.xml
streams-examples/streams-examples-local/elasticsearch-reindex/src/test/resources/application.conf
streams-examples/streams-examples-local/mongo-elasticsearch-sync/pom.xml
streams-examples/streams-examples-local/mongo-elasticsearch-sync/src/test/resources/application.conf
streams-examples/streams-examples-local/twitter-follow-neo4j/src/test/resources/application.conf
streams-examples/streams-examples-local/twitter-history-elasticsearch/src/test/resources/application.conf
streams-examples/streams-examples-local/twitter-userstream-elasticsearch/src/test/resources/application.conf

resolves STREAMS-598
STREAMS-596 should merge first

fix streams-examples ITs

---

streams-config/src/main/java/org/apache/streams/config/StreamsConfigurator.java

Resolve canonical class ancestor properties when path is set

---

streams-config/src/main/java/org/apache/streams/config/ComponentConfigurator.java

Better handle ConfigExceptions in ComponentConfigurator

---

streams-contrib/streams-provider-facebook/src/main/jsonschema/org/apache/streams/facebook/graph/Page.json
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/SevenDaySearchProvider.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/SevenDaySearchProviderTask.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/ThirtyDaySearchProvider.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/ThirtyDaySearchProviderTask.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterEngagersProvider.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterFollowersIdsProviderTask.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterFollowersListProviderTask.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterFollowingProvider.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterFriendsIdsProviderTask.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterFriendsListProviderTask.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterRetweetsTask.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterTimelineProvider.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterTimelineProviderTask.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterUserInformationProvider.java
streams-core/src/main/java/org/apache/streams/core/util/ExecutorUtils.java
streams-core/src/main/java/org/apache/streams/core/util/QueueUtils.java

adds Callable interfaces to twitter providers
includes some helpful refactoring

resolves STREAMS-605

---

streams-contrib/streams-provider-facebook/src/main/templates/facebook.ttl.ftl

STREAMS-618: Add message activities in facebook AS2.0 TTL output (https://issues.apache.org/jira/browse/STREAMS-618)

resolves STREAMS-618

---

streams-contrib/streams-provider-facebook/src/main/templates/facebook.ttl.ftl

resolves STREAMS-625
resolves STREAMS-627
resolves STREAMS-628

resolves STREAMS-625 STREAMS-627 STREAMS-628

---

streams-contrib/streams-provider-linkedin/src/main/templates/linkedin.ttl.ftl

also normalize more phone numbers

resolves STREAMS-626

---

streams-cli/src/test/resources/test.ttl.ftl
streams-contrib/streams-provider-facebook/src/main/templates/facebook.ttl.ftl
streams-contrib/streams-provider-instagram/src/main/templates/instagram.ttl.ftl
streams-contrib/streams-provider-linkedin/src/main/templates/linkedin.ttl.ftl
streams-contrib/streams-provider-twitter/src/main/templates/twitter.ttl.ftl

resolves STREAMS-616: Convert timestamps to xsd:datetime (ISO8601) in AS2.0 TTL outputs (https://issues.apache.org/jira/browse/STREAMS-616)

resolves STREAMS-616

---

streams-contrib/streams-provider-twitter/src/main/templates/twitter.ttl.ftl

resolves STREAMS-629: Add Direct Messages to twitter AS2.0 TTL output (https://issues.apache.org/jira/browse/STREAMS-629)

resolves STREAMS-629

---

streams-contrib/streams-provider-twitter/src/main/templates/twitter.ttl.ftl

Add Tweets to twitter AS2.0 TTL output

resolves STREAMS-630

---

streams-contrib/streams-persist-kafka/pom.xml
streams-contrib/streams-persist-kafka/src/main/java/org/apache/streams/kafka/KafkaPersistReader.java
streams-contrib/streams-persist-kafka/src/main/java/org/apache/streams/kafka/KafkaPersistWriter.java
streams-contrib/streams-persist-kafka/src/main/jsonschema/org/apache/streams/kafka/KafkaReaderConfiguration.json
streams-contrib/streams-persist-kafka/src/main/jsonschema/org/apache/streams/kafka/KafkaWriterConfiguration.json

STREAMS-633: kafka config

---

streams-contrib/pom.xml
streams-contrib/streams-processor-fullcontact/pom.xml
streams-contrib/streams-processor-fullcontact/src/main/java/org/apache/streams/fullcontact/CompanyEnrichment.java
streams-contrib/streams-processor-fullcontact/src/main/java/org/apache/streams/fullcontact/FullContact.java
streams-contrib/streams-processor-fullcontact/src/main/java/org/apache/streams/fullcontact/PersonEnrichment.java
streams-contrib/streams-processor-fullcontact/src/main/jsonschema/org/apache/streams/fullcontact/api/CompanySubscriptionRequest.json
streams-contrib/streams-processor-fullcontact/src/main/jsonschema/org/apache/streams/fullcontact/api/EnrichCompanyRequest.json
streams-contrib/streams-processor-fullcontact/src/main/jsonschema/org/apache/streams/fullcontact/api/EnrichPersonRequest.json
streams-contrib/streams-processor-fullcontact/src/main/jsonschema/org/apache/streams/fullcontact/api/PersonSubscriptionRequest.json
streams-contrib/streams-processor-fullcontact/src/main/jsonschema/org/apache/streams/fullcontact/config/FullContactConfiguration.json
streams-contrib/streams-processor-fullcontact/src/main/jsonschema/org/apache/streams/fullcontact/pojo/CompanyDetails.json
streams-contrib/streams-processor-fullcontact/src/main/jsonschema/org/apache/streams/fullcontact/pojo/CompanySummary.json
streams-contrib/streams-processor-fullcontact/src/main/jsonschema/org/apache/streams/fullcontact/pojo/CompanyTrafficRank.json
streams-contrib/streams-processor-fullcontact/src/main/jsonschema/org/apache/streams/fullcontact/pojo/Day.json
streams-contrib/streams-processor-fullcontact/src/main/jsonschema/org/apache/streams/fullcontact/pojo/Group.json
streams-contrib/streams-processor-fullcontact/src/main/jsonschema/org/apache/streams/fullcontact/pojo/PersonDetails.json
streams-contrib/streams-processor-fullcontact/src/main/jsonschema/org/apache/streams/fullcontact/pojo/PersonEmploymentItem.json
streams-contrib/streams-processor-fullcontact/src/main/jsonschema/org/apache/streams/fullcontact/pojo/PersonInterestItem.json
streams-contrib/streams-processor-fullcontact/src/main/jsonschema/org/apache/streams/fullcontact/pojo/PersonPhoto.json
streams-contrib/streams-processor-fullcontact/src/main/jsonschema/org/apache/streams/fullcontact/pojo/PersonProfile.json
streams-contrib/streams-processor-fullcontact/src/main/jsonschema/org/apache/streams/fullcontact/pojo/PersonProfiles.json
streams-contrib/streams-processor-fullcontact/src/main/jsonschema/org/apache/streams/fullcontact/pojo/PersonSummary.json
streams-contrib/streams-processor-fullcontact/src/main/jsonschema/org/apache/streams/fullcontact/pojo/PersonURL.json

STREAMS-631 - implements Full Contact SDK

---

streams-contrib/streams-amazon-aws/streams-persist-s3/src/main/java/org/apache/streams/s3/S3PersistReader.java

STREAMS-641 implement readAll() in S3PersistReader

---

streams-contrib/pom.xml
streams-contrib/streams-processor-peopledatalabs/pom.xml
streams-contrib/streams-processor-peopledatalabs/src/main/java/org/apache/streams/peopledatalabs/PeopleDataLabs.java
streams-contrib/streams-processor-peopledatalabs/src/main/java/org/apache/streams/peopledatalabs/PersonEnrichment.java
streams-contrib/streams-processor-peopledatalabs/src/main/jsonschema/org/apache/streams/peopledatalabs/api/BulkEnrichPersonRequest.json
streams-contrib/streams-processor-peopledatalabs/src/main/jsonschema/org/apache/streams/peopledatalabs/api/BulkEnrichPersonResponse.json
streams-contrib/streams-processor-peopledatalabs/src/main/jsonschema/org/apache/streams/peopledatalabs/api/EnrichPersonRequest.json
streams-contrib/streams-processor-peopledatalabs/src/main/jsonschema/org/apache/streams/peopledatalabs/api/EnrichPersonResponse.json
streams-contrib/streams-processor-peopledatalabs/src/main/jsonschema/org/apache/streams/peopledatalabs/config/PeopleDataLabsConfiguration.json
streams-contrib/streams-processor-peopledatalabs/src/main/jsonschema/org/apache/streams/peopledatalabs/pojo/EducationItem.json
streams-contrib/streams-processor-peopledatalabs/src/main/jsonschema/org/apache/streams/peopledatalabs/pojo/Email.json
streams-contrib/streams-processor-peopledatalabs/src/main/jsonschema/org/apache/streams/peopledatalabs/pojo/ExperienceItem.json
streams-contrib/streams-processor-peopledatalabs/src/main/jsonschema/org/apache/streams/peopledatalabs/pojo/IndustryItem.json
streams-contrib/streams-processor-peopledatalabs/src/main/jsonschema/org/apache/streams/peopledatalabs/pojo/InterestItem.json
streams-contrib/streams-processor-peopledatalabs/src/main/jsonschema/org/apache/streams/peopledatalabs/pojo/Location.json
streams-contrib/streams-processor-peopledatalabs/src/main/jsonschema/org/apache/streams/peopledatalabs/pojo/Name.json
streams-contrib/streams-processor-peopledatalabs/src/main/jsonschema/org/apache/streams/peopledatalabs/pojo/Person.json
streams-contrib/streams-processor-peopledatalabs/src/main/jsonschema/org/apache/streams/peopledatalabs/pojo/PhoneNumber.json
streams-contrib/streams-processor-peopledatalabs/src/main/jsonschema/org/apache/streams/peopledatalabs/pojo/Primary.json
streams-contrib/streams-processor-peopledatalabs/src/main/jsonschema/org/apache/streams/peopledatalabs/pojo/Profile.json
streams-contrib/streams-processor-peopledatalabs/src/main/jsonschema/org/apache/streams/peopledatalabs/pojo/SkillItem.json
streams-contrib/streams-processor-peopledatalabs/src/main/jsonschema/org/apache/streams/peopledatalabs/pojo/Title.json
streams-contrib/streams-processor-peopledatalabs/src/test/java/org/apache/streams/peopledatalabs/test/PeopleDataLabsIT.java
streams-contrib/streams-processor-peopledatalabs/src/test/resources/PeopleDataLabsIT.conf

integration with api hosted at peopledatalabs.com

STREAMS-644 streams-processor-peopledatalabs

---

streams-contrib/streams-processor-fullcontact/pom.xml
streams-contrib/streams-processor-fullcontact/src/main/java/org/apache/streams/fullcontact/FullContact.java
streams-contrib/streams-processor-fullcontact/src/main/jsonschema/org/apache/streams/fullcontact/api/EnrichPersonRequest.json
streams-contrib/streams-processor-fullcontact/src/main/jsonschema/org/apache/streams/fullcontact/api/LocationQuery.json
streams-contrib/streams-processor-fullcontact/src/main/jsonschema/org/apache/streams/fullcontact/api/NameQuery.json
streams-contrib/streams-processor-fullcontact/src/main/jsonschema/org/apache/streams/fullcontact/api/ProfileQuery.json
streams-contrib/streams-processor-fullcontact/src/main/jsonschema/org/apache/streams/fullcontact/config/FullContactConfiguration.json

I'm satisfied with this from local testing
There's another PR coming for STREAMS-645 integration testing for streams-processor-fullcontact
Containing integration tests that will demonstrate it works, BYO API token

STREAMS-646 support new Multi-Field requests in streams-processor-fullcontact

---

streams-contrib/streams-processor-fullcontact/src/main/resources/fullcontact.ttl
streams-contrib/streams-processor-fullcontact/src/main/scala/org/apache/streams/fullcontact/FullContactSocialGraph.scala
streams-contrib/streams-processor-fullcontact/src/main/scala/org/apache/streams/fullcontact/PersonEnrichmentProcessor.scala
streams-contrib/streams-processor-fullcontact/src/main/scala/org/apache/streams/fullcontact/util/AffinityOrdering.scala
streams-contrib/streams-processor-fullcontact/src/main/scala/org/apache/streams/fullcontact/util/FullContactUtils.scala

https://issues.apache.org/jira/browse/STREAMS-647

STREAMS-647 AS 2.0 RDF serialization in streams-processor-fullcontact

---

streams-contrib/streams-processor-fullcontact/src/main/java/org/apache/streams/fullcontact/FullContact.java
streams-contrib/streams-processor-fullcontact/src/main/java/org/apache/streams/fullcontact/PersonEnrichment.java
streams-contrib/streams-processor-fullcontact/src/main/jsonschema/org/apache/streams/fullcontact/api/EnrichPersonResponse.json
streams-contrib/streams-processor-fullcontact/src/test/java/org/apache/streams/fullcontact/test/FullContactIT.java
streams-contrib/streams-processor-fullcontact/src/test/resources/FullContactIT/FullContactIT.conf

https://issues.apache.org/jira/browse/STREAMS-650

resolves STREAMS-650

---

streams-contrib/streams-processor-peopledatalabs/src/main/java/org/apache/streams/peopledatalabs/PeopleDataLabs.java
streams-contrib/streams-processor-peopledatalabs/src/main/java/org/apache/streams/peopledatalabs/PersonEnrichment.java
streams-contrib/streams-processor-peopledatalabs/src/main/jsonschema/org/apache/streams/peopledatalabs/api/BulkEnrichPersonResponseItem.json
streams-contrib/streams-processor-peopledatalabs/src/main/jsonschema/org/apache/streams/peopledatalabs/api/EnrichPersonRequest.json
streams-contrib/streams-processor-peopledatalabs/src/test/java/org/apache/streams/peopledatalabs/test/PeopleDataLabsIT.java
streams-contrib/streams-processor-peopledatalabs/src/test/resources/PeopleDataLabsIT/PeopleDataLabsIT.conf

STREAMS-652 alter PeopleDataLabs interface and implementation to pass-through misses as well as hits

resolves STREAMS-652

---

pom.xml
release.sh
verify.sh

https://issues.apache.org/jira/browse/STREAMS-655

STREAMS-655 remove integration testing from release script

---

streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/api/AccountActivity.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/api/Twitter.java

resolves STREAMS-662
also organized imports, indentation, interface signatures in impacted files

STREAMS-662: implement re-enable account activity webhook endpoint

---

pom.xml
publish-rc.sh
streams-examples/src/site/markdown/index.md
streams-examples/streams-examples-flink/flink-twitter-collection/README.md
streams-examples/streams-examples-local/elasticsearch-hdfs/README.md
streams-examples/streams-examples-local/elasticsearch-hdfs/src/site/markdown/ElasticsearchHdfs.md
streams-examples/streams-examples-local/elasticsearch-hdfs/src/site/markdown/HdfsElasticsearch.md
streams-examples/streams-examples-local/elasticsearch-reindex/README.md
streams-examples/streams-examples-local/elasticsearch-reindex/src/site/markdown/ElasticsearchReindex.md
streams-examples/streams-examples-local/mongo-elasticsearch-sync/README.md
streams-examples/streams-examples-local/mongo-elasticsearch-sync/src/site/markdown/MongoElasticsearchSync.md
streams-examples/streams-examples-local/twitter-follow-neo4j/README.md
streams-examples/streams-examples-local/twitter-follow-neo4j/src/site/markdown/TwitterFollowNeo4j.md
streams-examples/streams-examples-local/twitter-history-elasticsearch/README.md
streams-examples/streams-examples-local/twitter-history-elasticsearch/src/site/markdown/TwitterHistoryElasticsearch.md
streams-examples/streams-examples-local/twitter-userstream-elasticsearch/README.md
streams-examples/streams-examples-local/twitter-userstream-elasticsearch/src/site/markdown/TwitterUserstreamElasticsearch.md

STREAMS-663: Fix DISCLAIMER

---

.github/workflows/streams-ci-workflow.yml

STREAMS-666: ensure rat check passes to prepare for 0.7.0 release

---

streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterFollowingProvider.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterTimelineProvider.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterUserInformationProvider.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterUserInformationProviderTask.java
streams-examples/streams-examples-flink/flink-twitter-collection/pom.xml
streams-examples/streams-examples-flink/flink-twitter-collection/src/main/scala/org/apache/streams/examples/flink/FlinkBase.scala
streams-examples/streams-examples-flink/flink-twitter-collection/src/main/scala/org/apache/streams/examples/flink/twitter/collection/FlinkTwitterFollowingPipeline.scala
streams-examples/streams-examples-flink/flink-twitter-collection/src/main/scala/org/apache/streams/examples/flink/twitter/collection/FlinkTwitterPostsPipeline.scala
streams-examples/streams-examples-flink/flink-twitter-collection/src/main/scala/org/apache/streams/examples/flink/twitter/collection/FlinkTwitterSpritzerPipeline.scala
streams-examples/streams-examples-flink/flink-twitter-collection/src/main/scala/org/apache/streams/examples/flink/twitter/collection/FlinkTwitterUserInformationPipeline.scala
streams-examples/streams-examples-flink/flink-twitter-collection/src/main/scala/org/apache/streams/examples/flink/twitter/collection/FollowingCollectorFlatMapFunction.scala
streams-examples/streams-examples-flink/flink-twitter-collection/src/main/scala/org/apache/streams/examples/flink/twitter/collection/TimelineCollectorFlatMapFunction.scala
streams-examples/streams-examples-flink/flink-twitter-collection/src/main/scala/org/apache/streams/examples/flink/twitter/collection/UserInformationCollectorFlatMapFunction.scala
streams-examples/streams-examples-flink/flink-twitter-collection/src/test/resources/FlinkTwitterFollowingPipelineFollowersIT.conf
streams-examples/streams-examples-flink/flink-twitter-collection/src/test/resources/FlinkTwitterFollowingPipelineFriendsIT.conf
streams-examples/streams-examples-flink/flink-twitter-collection/src/test/resources/FlinkTwitterPostsPipelineIT.conf
streams-examples/streams-examples-flink/flink-twitter-collection/src/test/resources/FlinkTwitterUserInformationPipelineIT.conf
streams-examples/streams-examples-flink/flink-twitter-collection/src/test/resources/testng.xml
streams-examples/streams-examples-flink/flink-twitter-collection/src/test/scala/org/apache/streams/examples/flink/twitter/test/FlinkTwitterFollowingPipelineFollowersIT.scala
streams-examples/streams-examples-flink/flink-twitter-collection/src/test/scala/org/apache/streams/examples/flink/twitter/test/FlinkTwitterFollowingPipelineFriendsIT.scala
streams-examples/streams-examples-flink/flink-twitter-collection/src/test/scala/org/apache/streams/examples/flink/twitter/test/FlinkTwitterPostsPipelineIT.scala
streams-examples/streams-examples-flink/flink-twitter-collection/src/test/scala/org/apache/streams/examples/flink/twitter/test/FlinkTwitterSpritzerPipelineIT.scala
streams-examples/streams-examples-flink/flink-twitter-collection/src/test/scala/org/apache/streams/examples/flink/twitter/test/FlinkTwitterUserInformationPipelineIT.scala

STREAMS-668
upgrade flink examples to latest flink version 1.11.1
small improvements to twitter flink pipelines
also improved threading and consistency throughout streams-provider-twitter

STREAMS-668 upgrade flink examples to latest flink version

---

streams-examples/streams-examples-flink/flink-twitter-collection/pom.xml
streams-examples/streams-examples-flink/flink-twitter-collection/src/main/jsonschema/StreamsFlinkConfiguration.json
streams-examples/streams-examples-flink/flink-twitter-collection/src/main/scala/org/apache/streams/examples/flink/FlinkBase.scala
streams-examples/streams-examples-flink/flink-twitter-collection/src/main/scala/org/apache/streams/examples/flink/twitter/collection/FlinkTwitterFollowingPipeline.scala
streams-examples/streams-examples-flink/flink-twitter-collection/src/main/scala/org/apache/streams/examples/flink/twitter/collection/FlinkTwitterPostsPipeline.scala
streams-examples/streams-examples-flink/flink-twitter-collection/src/main/scala/org/apache/streams/examples/flink/twitter/collection/FlinkTwitterUserInformationPipeline.scala
streams-examples/streams-examples-flink/flink-twitter-collection/src/main/scala/org/apache/streams/examples/flink/twitter/collection/FollowingCollectorFlatMapFunction.scala
streams-examples/streams-examples-flink/flink-twitter-collection/src/main/scala/org/apache/streams/examples/flink/twitter/collection/TimelineCollectorFlatMapFunction.scala

remove unnecessary keying and use GlobalWindow in streams-examples-flink/flink-twitter-collection

resolves STREAMS-676

---

streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/api/Twitter.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/SevenDaySearchProvider.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/SevenDaySearchProviderTask.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/ThirtyDaySearchProvider.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/ThirtyDaySearchProviderTask.java
streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/TwitterTimelineProviderTask.java
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/config/TwitterTimelineProviderConfiguration.json

resolves STREAMS-677
resolves STREAMS-680

STREAMS-677,STREAMS-680

---

streams-contrib/streams-provider-twitter/src/main/java/org/apache/streams/twitter/provider/ThirtyDaySearchProvider.java
streams-contrib/streams-provider-twitter/src/main/jsonschema/org/apache/streams/twitter/config/ThirtyDaySearchProviderConfiguration.json

STREAMS-681: add support for using fromDate and toDate in ThirtyDaySearchProvider

---

pom.xml
streams-components/streams-converters/src/main/jsonschema/org/apache/streams/converter/ActivityConverterProcessorConfiguration.json
streams-components/streams-converters/src/main/jsonschema/org/apache/streams/converter/ActivityObjectConverterProcessorConfiguration.json
streams-contrib/streams-persist-elasticsearch/src/main/jsonschema/org/apache/streams/elasticsearch/ElasticsearchReaderConfiguration.json
streams-contrib/streams-persist-graph/src/main/jsonschema/org/apache/streams/graph/GraphReaderConfiguration.json
streams-contrib/streams-provider-instagram/src/main/java/org/apache/streams/instagram/serializer/util/InstagramActivityUtil.java
streams-contrib/streams-provider-instagram/src/main/jsonschema/org/apache/streams/instagram/api/CommentsResponse.json
streams-contrib/streams-provider-instagram/src/main/jsonschema/org/apache/streams/instagram/api/RecentMediaResponse.json
streams-contrib/streams-provider-instagram/src/main/jsonschema/org/apache/streams/instagram/api/SearchMediaResponse.json
streams-contrib/streams-provider-instagram/src/main/jsonschema/org/apache/streams/instagram/api/SearchUsersResponse.json
streams-contrib/streams-provider-instagram/src/main/jsonschema/org/apache/streams/instagram/api/UserInfoResponse.json
streams-contrib/streams-provider-instagram/src/main/jsonschema/org/apache/streams/instagram/api/UsersInfoResponse.json
streams-contrib/streams-provider-instagram/src/main/jsonschema/org/apache/streams/instagram/pojo/Media.json
streams-contrib/streams-provider-instagram/src/main/jsonschema/org/apache/streams/instagram/pojo/MediaItem.json
streams-contrib/streams-provider-linkedin/pom.xml
streams-examples/streams-examples-local/elasticsearch-hdfs/src/main/jsonschema/ElasticsearchHdfsConfiguration.json
streams-examples/streams-examples-local/elasticsearch-hdfs/src/main/jsonschema/HdfsElasticsearchConfiguration.json
streams-examples/streams-examples-local/elasticsearch-reindex/src/main/jsonschema/ElasticsearchReindexConfiguration.json
streams-examples/streams-examples-local/mongo-elasticsearch-sync/src/main/jsonschema/MongoElasticsearchSyncConfiguration.json
streams-examples/streams-examples-local/twitter-follow-neo4j/src/main/jsonschema/TwitterFollowNeo4jConfiguration.json
streams-examples/streams-examples-local/twitter-history-elasticsearch/src/main/jsonschema/TwitterHistoryElasticsearchConfiguration.json
streams-examples/streams-examples-local/twitter-userstream-elasticsearch/src/main/jsonschema/TwitterUserstreamElasticsearchConfiguration.json
streams-plugins/streams-plugin-pojo/src/main/java/org/apache/streams/plugins/StreamsPojoGenerationConfig.java
streams-plugins/streams-plugin-pojo/src/main/java/org/apache/streams/plugins/StreamsPojoRuleLogger.java
streams-plugins/streams-plugin-pojo/src/main/java/org/apache/streams/plugins/StreamsPojoSourceGenerator.java
streams-plugins/streams-plugin-pojo/src/main/java/org/apache/streams/plugins/StreamsPojoSourceGeneratorMojo.java
streams-plugins/streams-plugin-pojo/src/test/java/org/apache/streams/plugins/test/StreamsPojoSourceGeneratorTest.java
streams-util/src/main/java/org/apache/streams/util/PropertyUtil.java
streams-util/src/main/java/org/apache/streams/util/schema/SchemaStoreImpl.java

because there were syntax changes in the new version, had to tweak a lot of json schema files and some utility classes

resolves STREAMS-683: upgrade jsonschema2pojo usage to modern version

---

.github/workflows/build.yml
.github/workflows/publish-snapshot.yml

chore: publish maven snapshots (#556)

---

.asf.yaml

Signed-off-by: Steve Blackmon <sblackmon@apache.org>
#561

chore: notifications (#561)
